# Generated by Django 5.0.3 on 2025-01-26 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_customer_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Health_Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benfek', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=8)),
                ('phone', models.CharField(max_length=15)),
                ('current_medication', models.CharField(blank=True, max_length=256, null=True)),
                ('family_condition', models.CharField(blank=True, max_length=256, null=True)),
                ('have_health_condition', models.CharField(blank=True, max_length=3, null=True)),
                ('health_condition', models.CharField(blank=True, max_length=256, null=True)),
                ('allergies', models.CharField(blank=True, max_length=1000, null=True)),
                ('scary_issue', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
