# Generated by Django 5.0.3 on 2025-01-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplement',
            name='description',
        ),
        migrations.AddField(
            model_name='supplement',
            name='expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
