# Generated by Django 5.0.3 on 2025-01-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customer_address_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
